### ISSUE TITLE
Change the cli command style

### ISSUE THREAD

**Issue by fzerorubigd** [ph4r5h4d/wait4it#47]
Currently the commands are like 
```
wait4it -type=xxx -flag1 -flag2
``` 
The problem is if the `flag1` is just for type `xxx` you can use it on type `yyy` but without any effect. 
my suggestion is to change the cli to something like this (it is breaking change so for the next version) 

```
wait4it type -flag-only-for-this-type -global-flag
```

then we can tie a flag to its own type. also the cli is cleaner (in my opinion :D )

**Comment by ph4r5h4d** [comment]
I agree, it's an issue now.
But I need a little bit more info, like for HTTP check we will have something like this?  
`wait4it HTTP -h=domain.com -status-code=301 -t=60`
or with a prefix:  
`wait4it HTTP -http-host=domain.com -http-status-code=301 -global-timeout=60`
or we can do also something like this:
`wait4it HTTP  -timeout=60 -additional-attributes=h=domain.com  -additonal-attributes=status-code=301`

The issue is clear to me but how you want to solve it, is not completely clear.

**Comment by ph4r5h4d** [comment]
I'm making some improvements, I've decided not to move forward with this change because it's a breaking change, and it's not adding much value to the project.
